# Generated by Django 4.1.4 on 2022-12-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('price', models.IntegerField(verbose_name='Стоимость блюда')),
                ('size', models.IntegerField(verbose_name='Размер блюда')),
                ('meal_type', models.CharField(choices=[('Горячие блюда', 'hot_meals'), ('Десерты', 'deserts'), ('Напитки', 'drinks'), ('NO_TYPE', 'no_type')], default='NO_TYPE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MealClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateField(verbose_name='Дата клика')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe_core_app.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
