# Generated by Django 4.1.4 on 2022-12-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0002_alter_mealclick_click_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meal',
            table='meal',
        ),
        migrations.AlterModelTable(
            name='mealclick',
            table='mealclick',
        ),
    ]
