# Generated by Django 4.1.4 on 2022-12-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0003_alter_meal_table_alter_mealclick_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mealclick',
            table=None,
        ),
    ]
