# Generated by Django 4.1.4 on 2022-12-30 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe_core_app', '0004_alter_meal_table_alter_mealclick_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealclick',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe_core_app.meal', verbose_name='meal'),
        ),
        migrations.AlterField(
            model_name='mealclick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
